name: "haap"
description: "HA access point"
version: "1.0.7"
slug: "haap"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
host_dbus: true
privileged: true
map:
  - config:rw
