name: Raspberry Pi Router
description: Configures the Raspberry Pi 5 to act as a network router between end0 and enu1
version: 1.0.0
slug: rpi-router
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: https://github.com/micmoc95/HA-RPI/RpiRouter
